---
- name: Deploy airports
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create airports namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: airports
            labels:
              role: app
    - name: airports deployments
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: airports-deployment
            namespace: airports
            labels:
              role: app
          spec:
            replicas: 1
            selector:
              matchLabels:
                role: app
            template:
              metadata:
                labels:
                  role: app
              spec:
                containers:
                - name: app
                  image: yazeed505/airports-assembly:1.0.1
                  ports:
                  - containerPort: 8080

    - name: airports service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: airports-svc
            namespace: airports
          spec:
            selector:
              role: app
            ports:
              - protocol: TCP
                port: 8000
                targetPort: 8080
                nodePort: 32002
            type: NodePort

    - name: airports ingress
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: airports-ingress
            namespace: airports
          spec:
            rules:
              - http:
                  paths:
                    - path: /airports
                      pathType: Prefix
                      backend:
                        service:
                          name: airports-svc
                          port:
                            number: 8000