name: airports
replicaCount: 1

image:
  repository: yazeed505/airports-assembly
  pullPolicy: Always
  tag: 1.0.1

podAnnotations:
  linkerd.io/inject: disabled

podSecurityContext: {}

service:
 type: NodePort
 port: 8000
 targetport: 8080

resources: 
  requests:
    cpu: 100m
    memory: 200m
container:
        port: 8080
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
namespace: "airports"

# For ingress
ingress:
  enabled: true
  hosts:
    - host: <host>
      paths:
      - /airports

##for liveness and readiness  
liveness:
  path: "/health/live"
  port: 8080
readiness:
  path: "/health/live"
  port: 8080