---
- name: Deploy applications + adding github repo
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Adding github project repo to Argocd
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: my-private-ssh-repo
            namespace: argocd
            labels:
              argocd.argoproj.io/secret-type: repository
          stringData:
            url: https://github.com/yazeed505/airport_and_country_project.git
    - name: countries application 
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: countries
            namespace: argocd
          spec:
            destination:
              name: ''
              namespace: countries
              server: 'https://kubernetes.default.svc'
            source:
              path: countries/helm
              repoURL: 'https://github.com/yazeed505/airport_and_country_project.git'
              targetRevision: HEAD
            sources: []
            project: default
            syncPolicy:
              automated:
                prune: false
                selfHeal: false
              syncOptions:
                - CreateNamespace=true
    - name: airports application 
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: airports
            namespace: argocd
          spec:
            destination:
              name: ''
              namespace: airports
              server: 'https://kubernetes.default.svc'
            source:
              path: airports/helm
              repoURL: 'https://github.com/yazeed505/airport_and_country_project.git'
              targetRevision: HEAD
            sources: []
            project: default
            syncPolicy:
              automated:
                prune: false
                selfHeal: false
              syncOptions:
                - CreateNamespace=true
