---
- name: Deploy applications + adding github repo
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Adding github project repo to Argocd
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: my-private-ssh-repo
            namespace: argocd
            labels:
              argocd.argoproj.io/secret-type: repository
          stringData:
            url: https://github.com/yazeed505/airport_and_country_project.git
    - name: countries application 
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: 'countries'
            namespace: argocd
          project: default
          source:
            repoURL: 'https://github.com/yazeed505/airport_and_country_project'
            path: countries/helm
            targetRevision: HEAD
            helm:
              valueFiles:
                - values.yaml
          destination:
            server: 'https://kubernetes.default.svc'
            namespace: countries
          syncPolicy:
            automated:
              selfHeal: true
            syncOptions:
              - CreateNamespace=true
    - name: airports application 
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: 'airports'
            namespace: argocd
          project: default
          source:
            repoURL: 'https://github.com/yazeed505/airport_and_country_project'
            path: airports/helm
            targetRevision: HEAD
            helm:
              valueFiles:
                - values.yaml
          destination:
            server: 'https://kubernetes.default.svc'
            namespace: airports
          syncPolicy:
            automated:
              selfHeal: true
            syncOptions:
              - CreateNamespace=true